USE WAREHOUSE WH_STREAMLIT_APP;

USE ROLE SYSADMIN;


CREATE OR REPLACE TABLE IOT_DATA.INGEST.SENSORS_DATA AS
WITH SENSORS AS
(
    SELECT SPLIT_PART(UPPER(uuid_string()),'-',1) AS SENSOR_ID
    FROM TABLE(GENERATOR(ROWCOUNT=>10)) --10 SENSORES
)
SELECT  
    SENSOR_ID,
    ROW_NUMBER() OVER(PARTITION BY SENSOR_ID ORDER BY SEQ4())AS ROW_NUMBER, -- GENERA UN VALOR
    DATEADD(MINUTE, ROW_NUMBER*5,'2022-09-22 00:00:00'::TIMESTAMP_NTZ ) AS READING_DATE, -- AGREGA EL VALOR POCISIONAL DEL ROW_NUMBER A LA FECHA
    UNIFORM(5, 50, RANDOM()) AS READING_VALUE --GENERA UN VALOR ENTRE 5 A 50
FROM
    TABLE(GENERATOR(ROWCOUNT =>2016 )),
    SENSORS --LECTURA CADA 5 MINUTOS POR 7 DIAS = 2016 LECTURAS | JOIN CARTESIANO
ORDER BY READING_DATE, SENSOR_ID;